name: movie_database_client
description: Dart client to search movies
version: 1.0.3
homepage: https://greycastle.se
repository: https://github.com/Greycastle/movie-database-client

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+4

dev_dependencies:
  test: