name: movie_database_client
description: Dart client to search movies
version: 0.0.1
author: David Dikman
homepage: https://greycastle.se

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http:

dev_dependencies:
  test: