name: movie_database_client
description: Very simple dart clieent wrapping the Open Movie Database API to list search responses to simple title queries. It returns titles, typee of title and poster images.
version: 1.0.3
homepage: https://greycastle.se
repository: https://github.com/Greycastle/movie-database-client

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.13.5

dev_dependencies:
  test: