name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Add settings
      env:
        settings: ${{ secrets.settings}}
      run: |
        echo "$env:settings" > test/settings.json
    - name: Run tests
      run: pub run test
